# -----------------------------------------------------------------------------
# System Imports
# -----------------------------------------------------------------------------

from typing import Tuple
from pathlib import Path

# -----------------------------------------------------------------------------
# Public Imports
# -----------------------------------------------------------------------------

import click

# -----------------------------------------------------------------------------
# Private Imports
# -----------------------------------------------------------------------------


from netcad.netcad_cli.common_opts import opt_devices, opt_network
from .clig_test import clig_test


@clig_test.command(name="configs")
@opt_devices()
@opt_network()
@click.option(
    "--configs-dir",
    help="network configs root-directory",
    type=click.Path(path_type=Path, resolve_path=True, exists=True, writable=True),
    default="configs",
)
def cli_audit_device(devices: Tuple[str], configs_dir: Path):
    """
    Audit the running device configs

    This command will compare the running config of the devices against the
    config generated by netcad.

    Not all devices will support a complete device audit as it requires specific
    features provided by the OS.

    OS support:
        * Arista EOS

    \f
    Parameters
    ----------
    devices
    configs_dir
    """
    pass
